### ISSUE TITLE
DukeGDX compatibility?

### ISSUE THREAD

**Issue by liPillON** [NightFright2k19/duke3d_widefix#6]
Judging by the existence of a dukegdx.def file, it should be there.
However when trying to use it under the latest BuildGDX version, the widefix package does not seems to have any effect.

BuildGDX warns about the existence of errors in the zip, just after having tried to load "scripts\widescreen.def" 
My setup consists of BuildGDX and the 4 official GRP files, placed in the port's root directory.
In the autoload folder I've placed your voxelpack and this.

Here's BuildGDX log file.. 
Can you help me understand what's going on?

[DukeGDX.log](https://github.com/NightFright2k19/duke3d_widefix/files/10369129/DukeGDX.log)

**Comment by NightFright2k19** [comment]
I am afraid the log provided yields absolutely nothing I can really work with. 

The only thing I could imagine is that DukeGDX doesn't support the ifcrc parameter (any more?), which would be bad. It is used to determine whether original game art is used (if it's modified, widescreen tiles are ignored).

It would be helpful to have someone with BuildGDX experience take a look.

**Comment by NightFright2k19** [comment]
Update:
I may have found out what's causing the issue. While I am using hex values for ifcrc in widescreen.def (which is fine at least for EDuke32 and Rednukem), DukeGDX apparently only recognizes decimals. Since this is done for all widescreen tiles, not a single one works if the wrong system is used.

This will require a new mod release. I'll look into it tomorrow, shouldn't take too much time.

**Comment by liPillON** [comment]
thank you
I myself was testing this, commenting-out all ifcrc statements
Naturally the issue then became having the same tile referenced by multiple tilefromtexture instructions, but at least the engine was able to through the other .def files

And so i found out other warnings, this time about the "artquality" keyword in skyboxes.def

**Comment by NightFright2k19** [comment]
Please check if everything works with this test build. If there are no issues, I will release this officially ASAP.
[duke3d_widefix-test.zip](https://github.com/NightFright2k19/duke3d_widefix/files/10370979/duke3d_widefix-test.zip)

**Comment by liPillON** [comment]
No errors and no warnings, however the help and credit screens seem to be off-center.
I'm attaching a screenshot with the game running windowed at 1280x720, but the issue is present at any fullscreen resolution too.
![Immagine 2023-01-09 091237](https://user-images.githubusercontent.com/48625273/211264657-f1248967-b2e8-4cfe-99a5-36eaf9722c12.png)

Moreover, the title screen does not seem to work, see here:
![Immagine 2023-01-09 091537](https://user-images.githubusercontent.com/48625273/211265063-49ffdb32-9b15-49b5-9bc3-236487a8ac1f.png)

**Comment by NightFright2k19** [comment]
OK, I did not know that DukeGDX does not support widescreen tiles for menus. Regarding that, there is absolutely nothing I can do since it's a port-sided issue.

That being considered, I guess it does not really make sense to use this mod with that specific port. On top of that, it already comes with its own widescreen tiles, which are identical with the ones you can find here, besides the additional menu definitions (which won't work, though).

**Comment by liPillON** [comment]
huh I did not know that gdx provided its own ws tiles, maybe there were none the last time I've used it a couple of years ago
I recently switched back from Raze (due to the latter having made some physics changes affecting Blood) and I'm still tinkering with the whole setup
sorry for wasting your time

**Comment by NightFright2k19** [comment]
DukeGDX comes with widescreen replacements for weapons, which is good enough for normal gaming purposes. What this mod provides on top are widescreen menu graphics, but only EDuke32, Rednukem and Raze support those.
